### ISSUE TITLE
Should ee16b/topics/16a-import be a symlink?

### ISSUE THREAD

**Issue by PTNobel** [hkntutoring/slides#1]
If the contents of that folder are literally just the contents of 16a copied, I feel like we should just do a symlink so that updates to 16a get propogated into 16b? Otherwise we should add a README explaining what is going on.

**Comment by GeoHutch** [comment]
I see arguments for both sides. non-symlink means that ee16b quest is "pinned", compiling it today vs tommorow can't change the results for non-ee16b reasons. This is kinda what I want, because we made the decision that these specific 16a slides would be good quest review, independent of future changes to 16a mt2 content.

But a symlink is generally more elegant, and, if future iterations of 16b keep the "quest" structure, it might be worth making it that much more maintainance-free to use the most up-to-date ee16a content.

(I also have doubts that future 16bs will actually keep the quest structure, so another option might be to just relegate these changes to an archival branch)

**Comment by PTNobel** [comment]
Then I think a README would be a wise idea to explain the decisions made and what we expect future people to do.
